Ansible 2
Otus-DevOps-2020-02/viktoriya666_infra pull request #13
Opened 2020-04-17 06:59 UTC by viktoriya666

# Выполнено ДЗ №11

 - [ + ] Основное ДЗ

## В процессе сделано:
- Playbook разбит на несколько play (app, db,deploy)
- Связан Packer с Ansible

## Как запустить проект:
 - Запустить ansible-playbook site.yml в директории ansible

## Как проверить работоспособность:
 - После деплоя перейти по ссылке http://<app_external_ip>:9292

## PR checklist
 - [ + ] Выставил label с номером домашнего задания
 - [ + ] Выставил label с темой домашнего задания

2020-04-17 08:55 UTC, viktoriya666 commented
Очень странные ошибки, все по gist, не понимаю почему ругается) А это может быть связано с тем, что прошлая ветка еще не вмержена в мастер? Я просто так ни разу не делала))

2020-04-17 10:02 UTC, mrgreyves requested changes
Здравствуйте!) packer_db.yml немного съехал, нужно подправить. packer_app.yml вот тут попробуйте оставить одну пустую строку в конце файла. Возвращаю в доработку, если что в слак.

2020-04-18 15:50 UTC, mrgreyves requested changes
Здравствуйте! Оставил комментарии к файлам, дз возвращаю на доработку.

2020-04-18 15:50 UTC, mrgreyves commented on ansible/reddit_app_multiple_plays.yml
> +---
Файлик съехал и не хватает новой строки

2020-04-18 15:50 UTC, mrgreyves commented on ansible/packer_db.yml
> +    hosts: all
Вот тут все съехало

2020-04-19 17:34 UTC, mrgreyves approved these changes
Здравствуйте!) Апрув!)

2020-04-19 18:34 UTC, merged