Play travis
Otus-DevOps-2020-02/viktoriya666_infra pull request #2
Opened 2020-03-12 19:41 UTC by viktoriya666

Нomework 4 completed:

- Configured integration with Travis.
- Fixed bugs in the build.
- Utility added PULL_REQUEST_TEMPLATE.

2020-03-13 07:25 UTC, mrgreyves requested changes
Здравствуйте!) Вам нужно починить тесты. ДЗ возвращаю на доработку.

2020-03-13 07:25 UTC, mrgreyves commented on play-travis/test.py
> +        self.assertEqual(1 + 1, 1)
Ошибочка закралась =)

2020-03-15 12:56 UTC, viktoriya666 commented on play-travis/test.py
> +        self.assertEqual(1 + 1, 1)
Тесты починила, запушила, что теперь нужно - закрыть этот пулл реквест и новый создать?

2020-03-15 17:06 UTC, mrgreyves commented on play-travis/test.py
> +        self.assertEqual(1 + 1, 1)
Нет!)

2020-03-15 17:06 UTC, mrgreyves approved these changes
Здравствуйте!) Апрув!)

2020-03-16 14:35 UTC, merged