Cloud bastion
Otus-DevOps-2020-02/viktoriya666_infra pull request #5
Opened 2020-03-21 07:51 UTC by viktoriya666

# Выполнено ДЗ № 5

 - [+] Основное ДЗ
 - [+] Задание со *

## В процессе сделано:
 - Соединение по VPN

## PR checklist
 - [+] Выставил label с номером домашнего задания
 - [+] Выставил label с темой домашнего задания

2020-03-21 10:11 UTC, mrgreyves requested changes
Здравствуйте!) Как вы там создаете ветки и пр, что тесты не запускаются?0_о

2020-03-21 10:45 UTC, viktoriya666 commented
Добрый день! Я в тревисе вижу что все ок, где еще смотреть) ветки создаю как обычно, через консоль гита

2020-03-27 05:39 UTC, mrgreyves requested changes
Здравствуйте!) Общались с вами в лс по поводу ваших пр =)

2020-04-02 05:37 UTC, viktoriya666 commented
Починила тесты

2020-04-02 13:54 UTC, mrgreyves requested changes
Здравствуйте!) Проверил ваше дз. К сожалению тесты красные, оставил комментарии к файлам. Так же вам стоит следить за пустыми строками в конце файлом. ДЗ возвращаю на доработку.

2020-04-02 13:54 UTC, mrgreyves commented on setup.vpn
> +#!/bin/bash
setupvpn.sh имя файла должно быть вот таким =)

2020-04-02 13:54 UTC, mrgreyves commented on README.md
> -testapp_IP = 35.189.216.81
В ридми стоит добавить адреса как бастион хоста так и внутрненнего хоста =)

2020-04-06 06:19 UTC, viktoriya666 reviewed
Имя файла изменила, коммент написала, new line в конце файла остаивила, прошу проеврить что еще может быть не так, вроде все по инструкции

2020-04-06 06:19 UTC, viktoriya666 commented on README.md
> -testapp_IP = 35.189.216.81
Красным выделено то, что из фала ведь удалено? У меня в следующем ПР был конфликт, я удалила этот текст из ридми( Он от следующего ДЗ
А то что зеленым, к этому ДЗ, там все адреса есть

2020-04-06 13:46 UTC, mrgreyves requested changes
Здравствуйте!) Тест не может распарсить IP адреса. Попробуйте перенести их в отдельные строки.

2020-04-08 07:49 UTC, mrgreyves approved these changes
Здравствуйте!) Вот теперь все более или менее корректно. Тесты наверняка проводились когда инфраструктура была уже выключена. Не буду вас дальше мучать. ДЗ принимаю!=)

2020-04-08 12:57 UTC, merged