Packer base
Otus-DevOps-2020-02/viktoriya666_infra pull request #7
Opened 2020-03-25 19:05 UTC by viktoriya666

# Выполнено ДЗ №7

 - [+] Основное ДЗ
 - [-] Задание со *

## В процессе сделано:
- Создан образ ВМ с помощью Packer
- Деплой приложения
- Созданы шаблоны с параметрами

## PR checklist
 - [+] Выставил label с темой домашнего задания

2020-03-27 05:39 UTC, mrgreyves requested changes
Здравствуйте!) Общались с вами в лс по поводу ваших пр =)

2020-04-02 05:36 UTC, viktoriya666 commented
Починила тесты

2020-04-02 13:56 UTC, mrgreyves requested changes
Здравствуйте!) У вас не хватает файла ubuntu16.json. Так же вам нужно проверить синтаксис в файле variables.json.example. ДЗ возвращаю на доработку.

2020-04-06 06:35 UTC, viktoriya666 commented
Все замечания устранила, почему снова и снова в билде ошибка 

> The command "curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-02/run.sh | bash" failed and exited with 100 during .

2020-04-06 13:47 UTC, mrgreyves commented
![image](https://user-images.githubusercontent.com/34331259/78565211-3dd9dd80-7826-11ea-8b7f-1c05e6683982.png)
Так нет же ошибки =)

2020-04-06 13:48 UTC, mrgreyves approved these changes
Здравствуйте!) Вот теперь апрув!)

2020-04-07 06:54 UTC, merged